name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: DVC pull
        run: |
          python -m pip install --upgrade pip
          # install DVC core plus the Google Drive plugin
          pip install "dvc[gdrive]"
          # now pull your data
          dvc pull
          
      - name: Lint with Ruff
        run: ruff check .

      - name: Run Pytest
        run: pytest tests/
