name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Install DVC with GDrive support
        run: |
          pip install "dvc[gdrive]"

      - name: Configure DVC to use bundled service account
        run: |
          dvc remote modify gdrive_remote \
            gdrive_service_account_json_file_path dvc.json

      - name: DVC pull
        run: dvc pull -r gdrive_remote

      - name: Lint with Ruff
        run: ruff check .

      - name: Run Pytest
        run: pytest tests/
