name: CML Evaluation - All Models

on:
  push:
    branches:
        - hydra-config-setup
        - main
        - phase3_v2
    paths:
      - '**/predict_model.py'
      - '**/cml_eval.py'
      - '.github/workflows/cml_all_models.yml'
  pull_request:

jobs:
  cml-eval:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            include:
                - model: cnn
                  first: true
                - model: mlp
                  first: false
                - model: xgboost
                  first: false


    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wandb scikit-learn matplotlib seaborn rich hydra-core tensorflow xgboost cml

      - name: 🧠 Run prediction for ${{ matrix.model }}
        run: |
          PYTHONPATH=. python mlops_randproject/models/predict_model.py model=${{ matrix.model }}

      - name: 📊 Generate evaluation report
        run: |
            CML_FIRST_MODEL=${{ matrix.first }} PYTHONPATH=. python mlops_randproject/cml_eval.py --model ${{ matrix.model }}

      - name: 💬 Comment CML report for ${{ matrix.model }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx cml comment metrics_report.md --update
