name: CI/CD Docker Build & Push

on:
  push:
    branches:
      - main
      - hydra-config-setup

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build & Push train image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/train_model.dockerfile
          push: true
          tags: yourdockerhubusername/mlops-train:latest

      - name: Build & Push predict image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/predict_model.dockerfile
          push: true
          tags: yourdockerhubusername/mlops-predict:latest
