
name: CI/CD - Predict Pipeline

on:
  push:
    branches:
      - hydra-config-setup
      - main
    paths:
      - 'dockerfiles/predict_model.dockerfile'
      - 'mlops_randproject/models/predict_model.py'
      - '.github/workflows/predict.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: ✨ Checkout code
        uses: actions/checkout@v3

      - name: ⚙ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔑 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ⚖️ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/predict_model.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-predict:latest
