model:
  _target_: mlops_randproject.model_zoo.build_cnn
  name: cnn
  filters:
  - 32
  - 64
  kernel_size: 3
  pool_size: 2
  dense_units: 128
  dropout: 0.5
  output: 10
  optimizer: adam
  conv_layers: 2
  learning_rate: 0.001
  epochs: 10
  batch_size: 32
predict:
  test_features_path: ${env:RUN_ENV_BASE, .}/artifacts/test_features.npy
  test_labels_path: ${env:RUN_ENV_BASE, .}/artifacts/test_labels.npy
  weights_path: ${env:RUN_ENV_BASE, .}/artifacts/model.weights.h5
  output_file: ${env:RUN_ENV_BASE, .}/artifacts/predictions_${model.name}.txt
data:
  path: data/raw
  sample_rate: 22050
train:
  test_size: 0.2
  random_state: 42
  batch_size: 32
  epochs: 100
  validation_split: 0.2
  early_stopping:
    monitor: val_loss
    patience: 10
    restore_best_weights: true
  reduce_lr_on_plateau:
    monitor: val_loss
    factor: 0.5
    patience: 5
    min_lr: 1.0e-06
